export const MAIN_ROUTE = "/"
export const ADMIN_ROUTE = "/admin"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const AUTORIZATION_ROUTE = "/autorization"
export const PROFILE_ROUTE = "/profile"
export const AUTH_ROUTE = "/auth"